<a href="https://colab.research.google.com/github/avganshina/diabetes_predictions/blob/main/diabetes_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Load the dataset
dataset = pd.read_csv('diabetes.csv')

# Print out part of the dataset to ensure proper loading
print(dataset.head())

# Print the shape of dataset
print(dataset.shape)

#Print the name of all columns
print(list(dataset.columns))

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
(768, 9)
['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']


In [2]:
# Deviding the data to the features and labels

x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

print(x[:10])
print(y[:10])

[[1.480e+02 7.200e+01 3.500e+01 0.000e+00 3.360e+01 6.270e-01 5.000e+01]
 [8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01 3.100e+01]
 [1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01 3.200e+01]
 [8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01 2.100e+01]
 [1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00 3.300e+01]
 [1.160e+02 7.400e+01 0.000e+00 0.000e+00 2.560e+01 2.010e-01 3.000e+01]
 [7.800e+01 5.000e+01 3.200e+01 8.800e+01 3.100e+01 2.480e-01 2.600e+01]
 [1.150e+02 0.000e+00 0.000e+00 0.000e+00 3.530e+01 1.340e-01 2.900e+01]
 [1.970e+02 7.000e+01 4.500e+01 5.430e+02 3.050e+01 1.580e-01 5.300e+01]
 [1.250e+02 9.600e+01 0.000e+00 0.000e+00 0.000e+00 2.320e-01 5.400e+01]]
[1 0 1 0 1 0 1 0 1 1]


In [3]:
# Splitting the data to training and test sets

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [4]:
# Scaling the dataset
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [5]:
# Creating the model
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(multi_class='ovr', random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(multi_class='ovr', random_state=0)

In [6]:
# Predicting the results
from sklearn.metrics import confusion_matrix, accuracy_score

predictions = classifier.predict(x_test)
cm = confusion_matrix(predictions, y_test)
print(cm)
accuracy_score(predictions, y_test)

[[96 19]
 [11 28]]


0.8051948051948052