<a href="https://colab.research.google.com/github/avganshina/diabetes_predictions/blob/main/diabetes_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd

# Load the dataset
dataset = pd.read_csv('data_ML.csv')

# Print out part of the dataset to ensure proper loading
print(dataset.head())

# Print the shape of dataset
print(dataset.shape)

#Print the name of all columns
print(list(dataset.columns))

   Age  Polyuria  Polydipsia  ...  muscle stiffness  Obesity  class
0   49         1           1  ...                 0        0      1
1   68         1           1  ...                 1        0      1
2   43         1           0  ...                 1        0      1
3   40         0           0  ...                 0        0      0
4   54         1           1  ...                 0        0      1

[5 rows x 15 columns]
(251, 15)
['Age', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching', 'Irritability', 'delayed healing', 'partial paresis', 'muscle stiffness', 'Obesity', 'class']


In [20]:
# Deviding the data to the features and labels

x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

print(x[:10])
print(y[:10])

[[1 1 0 1 0 0 1 1 0 0 0 0 0]
 [1 1 1 0 1 1 1 0 1 1 0 1 0]
 [1 0 0 0 1 0 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0 1 0 0]
 [1 1 0 1 1 0 1 1 0 1 1 1 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 1 1 1 1 1 0 0]
 [0 1 1 0 0 1 1 1 0 0 0 1 0]]
[1 1 1 0 1 1 0 0 1 1]


In [21]:
# Splitting the data to training and test sets

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [22]:
# Scaling the dataset
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [23]:
# Creating the model
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(multi_class='ovr', random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=0,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

In [24]:
# Predicting the results
from sklearn.metrics import confusion_matrix, accuracy_score

predictions = classifier.predict(x_test)
cm = confusion_matrix(predictions, y_test)
print(cm)
accuracy_score(predictions, y_test)

[[15  7]
 [ 5 24]]


0.7647058823529411